################################################################################
# Copyrights Â© 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
  - title: Getting Started
    link: docs/introduction/getting-started.md
    open: true
    
- sections:
    - title: Introduction
      link:
      open: true
      sections:
        - title: Before you start
          link: docs/introduction/overview.md
          open: true
        - title: Know our API structure
          link: docs/introduction/knowOurApiStructure.md
        - title: Make your first API call
          link: docs/introduction/makeYourFirstApiCall.md

- sections:
    - title: Resources and Guides
      link: 
       sections:
        - title: Register
          link: docs/resourcesAndGuides/register.md
          open: true
        - title: Authenticate
          link: docs/resourcesAndGuides/authenticate.md
        - title: Start Making Requests
          link: docs/resourcesAndGuides/startMakingRequests.md
        - title: Refresh An Access Token
          link: docs/resourcesAndGuides/refreshAnAccessToken.md
        - title: Session Termination
          link: docs/resourcesAndGuides/sessionTermination.md
        - title: Requirements and Limitations
          link: docs/resourcesAndGuides/requirementsAndLimitations.md
        - title: Versioning and Backwards Compatibility
          link: docs/resourcesAndGuides/versioningAndBackwardsCompatibility.md
        - title: Response Codes
          link: docs/resourcesAndGuides/responseCodes.md
        - title: Important to Know
          link: docs/resourcesAndGuides/importantToKnow.md
        - title: Sample Use Case Implementation
          link: docs/resourcesAndGuides/sampleUseCaseImplementation.md
        - title: Frequently asked questions
          link: docs/resourcesAndGuides/frequentlyAskedQuestions.md
        - title: API Glossary
          link: docs/resourcesAndGuides/apiGlossary.md

- sections:
  - title: API Domains
    link: 
       sections:
        - title: Health
          link: docs/apiDomains/health.md
          open: true
        - title: Users
          link: docs/apiDomains/users.md
        - title: Potential Payees
          link: docs/apiDomains/potentialPayees.md
        - title: Payees
          link: docs/apiDomains/payees.md
        - title: Payee Groups
          link: docs/apiDomains/payeeGroups.md
        - title: Merchants
          link: docs/apiDomains/merchants.md
        - title: Probable Merchants
          link: docs/apiDomains/probableMerchants.md
        - title: Reminders
          link: docs/apiDomains/reminders.md
        - title: ToDos
          link: docs/apiDomains/toDos.md
        - title: Bills
          link: docs/apiDomains/bills.md
        - title: E-bill Activation
          link: docs/apiDomains/eBillActivation.md
        - title: Bank Accounts
          link: docs/apiDomains/bankAccounts.md
        - title: Card Accounts
          link: docs/apiDomains/cardAccounts.md
        - title: Transaction Calendar
          link: docs/apiDomains/transactionCalendar.md
        - title: Transactions
          link: docs/apiDomains/transactions.md
        - title: Automatic Transactions
          link: docs/apiDomains/automaticTransactions.md
        - title: Messages
          link: docs/apiDomains/messages.md
        - title: Complex Objects
          link: docs/apiDomains/complexObjects.md
   
- sections:
  - title: Release Notes
    link: docs/releaseNotes/releaseNotes.md
    open: true

- sections:
  - title: Support
    link: docs/support/support.md
    open: true